#!/usr/bin/env bash
set -e

. "$(dirname $0)/lib/common"

cat PluginRequirements | grep "^plugin" | while read -r line || [[ -n "$line" ]]; do
  name="$(echo $line | awk '{print $2}')"
  existing_hash="nope"
  wanted_hash="$(echo $line | awk '{print $3}')"
  url="$(echo $line | awk '{print $4}')"
  file="$(echo $line | awk '{print $5}')"
  tmpdir=".tmp/plugins/$name"
  tmp="$tmpdir/$name.download"
  dest="plugins/$name.jar"

  if [ -f $dest ]; then
    existing_hash="$(shasum $dest | awk '{print $1}')"

    if [[ "$wanted_hash" == "$existing_hash" ]]; then
      echo "[$name] Already downloaded - skipping"
      continue
    fi
  fi

  echo "[$name] Downloading from $url"
  mkdir -p $tmpdir
  curl -o $tmp -L --silent $url

  # Extract zips
  if [ ! -z "$file" ]; then
    cd $tmpdir
    unzip -o $name.download
    tmp="$tmpdir/$file"
    cd $ROOT_DIR
  fi

  got_hash="$(shasum $tmp | awk '{print $1}')"

  if [[ "$wanted_hash" != "$got_hash" ]]; then
    echo "[$name] Error! Expecting hash $wanted_hash but got $got_hash"
    exit 1
  else
    if [[ "$existing_hash" == "$got_hash" ]]; then
      echo "[$name] Already up to date - skipping"
    else
      mv $tmp $dest
      echo "[$name] Installed to $dest"
    fi
    rm -rf $tmpdir
  fi
done
